import React from "react";
import styles from "./_background.module.scss";

function Background() {
  return (
    <div className={`${styles.container}`}>
      {/* right*/}
      <div className={`${styles.tile} ${styles.tile_1}`}></div>
      <div className={`${styles.tile} ${styles.tile_2}`}></div>
      <div className={`${styles.tile} ${styles.tile_3}`}></div>
      <div className={`${styles.tile} ${styles.tile_4}`}></div>
      <div className={`${styles.tile} ${styles.tile_5}`}></div>
      <div className={`${styles.tile} ${styles.tile_6}`}></div>
      <div className={`${styles.tile} ${styles.tile_7}`}></div>
      <div className={`${styles.tile} ${styles.tile_8}`}></div>
      <div className={`${styles.tile} ${styles.tile_9}`}></div>
      <div className={`${styles.tile} ${styles.tile_10}`}></div>
      <div className={`${styles.tile} ${styles.tile_11}`}></div>
      <div className={`${styles.tile} ${styles.tile_12}`}></div>
      <div className={`${styles.tile} ${styles.tile_13}`}></div>
      <div className={`${styles.tile} ${styles.tile_14}`}></div>
      <div className={`${styles.tile} ${styles.tile_15}`}></div>
      <div className={`${styles.tile} ${styles.tile_16}`}></div>
      <div className={`${styles.tile} ${styles.tile_17}`}></div>
      <div className={`${styles.tile} ${styles.tile_18}`}></div>
      <div className={`${styles.tile} ${styles.tile_19}`}></div>
      <div className={`${styles.tile} ${styles.tile_20}`}></div>
      <div className={`${styles.tile} ${styles.tile_21}`}></div>
      <div className={`${styles.tile} ${styles.tile_22}`}></div>
      <div className={`${styles.tile} ${styles.tile_23}`}></div>
      <div className={`${styles.tile} ${styles.tile_24}`}></div>
      <div className={`${styles.tile} ${styles.tile_25}`}></div>
      <div className={`${styles.tile} ${styles.tile_26}`}></div>
      <div className={`${styles.tile} ${styles.tile_27}`}></div>
      <div className={`${styles.tile} ${styles.tile_28}`}></div>
      <div className={`${styles.tile} ${styles.tile_29}`}></div>
      <div className={`${styles.tile} ${styles.tile_30}`}></div>
      <div className={`${styles.tile} ${styles.tile_31}`}></div>
      <div className={`${styles.tile} ${styles.tile_32}`}></div>
      <div className={`${styles.tile} ${styles.tile_33}`}></div>
      <div className={`${styles.tile} ${styles.tile_34}`}></div>
      <div className={`${styles.tile} ${styles.tile_35}`}></div>
      <div className={`${styles.tile} ${styles.tile_36}`}></div>
      <div className={`${styles.tile} ${styles.tile_37}`}></div>
      <div className={`${styles.tile} ${styles.tile_38}`}></div>
      <div className={`${styles.tile} ${styles.tile_39}`}></div>
      <div className={`${styles.tile} ${styles.tile_40}`}></div>
      <div className={`${styles.tile} ${styles.tile_41}`}></div>
      <div className={`${styles.tile} ${styles.tile_42}`}></div>
      <div className={`${styles.tile} ${styles.tile_43}`}></div>
      <div className={`${styles.tile} ${styles.tile_44}`}></div>
      <div className={`${styles.tile} ${styles.tile_45}`}></div>
      <div className={`${styles.tile} ${styles.tile_46}`}></div>

      {/* right-2 */}
      <div className={`${styles.tile} ${styles.tile_47}`}></div>
      <div className={`${styles.tile} ${styles.tile_48}`}></div>
      <div className={`${styles.tile} ${styles.tile_49}`}></div>
      <div className={`${styles.tile} ${styles.tile_50}`}></div>
      <div className={`${styles.tile} ${styles.tile_51}`}></div>
      <div className={`${styles.tile} ${styles.tile_52}`}></div>
      <div className={`${styles.tile} ${styles.tile_53}`}></div>
      <div className={`${styles.tile} ${styles.tile_54}`}></div>
      <div className={`${styles.tile} ${styles.tile_55}`}></div>
      <div className={`${styles.tile} ${styles.tile_56}`}></div>
      <div className={`${styles.tile} ${styles.tile_57}`}></div>
      <div className={`${styles.tile} ${styles.tile_58}`}></div>
      <div className={`${styles.tile} ${styles.tile_59}`}></div>
      <div className={`${styles.tile} ${styles.tile_60}`}></div>
      <div className={`${styles.tile} ${styles.tile_61}`}></div>
      <div className={`${styles.tile} ${styles.tile_62}`}></div>
      <div className={`${styles.tile} ${styles.tile_63}`}></div>
      <div className={`${styles.tile} ${styles.tile_64}`}></div>
      <div className={`${styles.tile} ${styles.tile_65}`}></div>
      <div className={`${styles.tile} ${styles.tile_66}`}></div>
      <div className={`${styles.tile} ${styles.tile_67}`}></div>

      {/* left */}
      <div className={`${styles.tile} ${styles.tile_68}`}></div>
      <div className={`${styles.tile} ${styles.tile_69}`}></div>
      <div className={`${styles.tile} ${styles.tile_70}`}></div>
      <div className={`${styles.tile} ${styles.tile_71}`}></div>
      <div className={`${styles.tile} ${styles.tile_72}`}></div>
      <div className={`${styles.tile} ${styles.tile_73}`}></div>
      <div className={`${styles.tile} ${styles.tile_74}`}></div>
      <div className={`${styles.tile} ${styles.tile_75}`}></div>
      <div className={`${styles.tile} ${styles.tile_76}`}></div>
      <div className={`${styles.tile} ${styles.tile_77}`}></div>
      <div className={`${styles.tile} ${styles.tile_78}`}></div>
      <div className={`${styles.tile} ${styles.tile_79}`}></div>
      <div className={`${styles.tile} ${styles.tile_80}`}></div>
      <div className={`${styles.tile} ${styles.tile_81}`}></div>
      <div className={`${styles.tile} ${styles.tile_82}`}></div>
      <div className={`${styles.tile} ${styles.tile_83}`}></div>
      <div className={`${styles.tile} ${styles.tile_84}`}></div>
      <div className={`${styles.tile} ${styles.tile_85}`}></div>
      <div className={`${styles.tile} ${styles.tile_86}`}></div>
      <div className={`${styles.tile} ${styles.tile_87}`}></div>
      <div className={`${styles.tile} ${styles.tile_88}`}></div>
      <div className={`${styles.tile} ${styles.tile_89}`}></div>
      <div className={`${styles.tile} ${styles.tile_90}`}></div>
      <div className={`${styles.tile} ${styles.tile_91}`}></div>
      <div className={`${styles.tile} ${styles.tile_92}`}></div>
      <div className={`${styles.tile} ${styles.tile_93}`}></div>
      <div className={`${styles.tile} ${styles.tile_94}`}></div>
      <div className={`${styles.tile} ${styles.tile_95}`}></div>
      <div className={`${styles.tile} ${styles.tile_96}`}></div>
      <div className={`${styles.tile} ${styles.tile_97}`}></div>
      <div className={`${styles.tile} ${styles.tile_98}`}></div>
      <div className={`${styles.tile} ${styles.tile_99}`}></div>
      <div className={`${styles.tile} ${styles.tile_100}`}></div>
      <div className={`${styles.tile} ${styles.tile_101}`}></div>
      <div className={`${styles.tile} ${styles.tile_102}`}></div>
      <div className={`${styles.tile} ${styles.tile_103}`}></div>
      <div className={`${styles.tile} ${styles.tile_104}`}></div>
      <div className={`${styles.tile} ${styles.tile_105}`}></div>
      <div className={`${styles.tile} ${styles.tile_106}`}></div>
      <div className={`${styles.tile} ${styles.tile_107}`}></div>
      <div className={`${styles.tile} ${styles.tile_108}`}></div>
      <div className={`${styles.tile} ${styles.tile_109}`}></div>
      <div className={`${styles.tile} ${styles.tile_110}`}></div>
      <div className={`${styles.tile} ${styles.tile_111}`}></div>
      <div className={`${styles.tile} ${styles.tile_112}`}></div>
      <div className={`${styles.tile} ${styles.tile_113}`}></div>
      <div className={`${styles.tile} ${styles.tile_114}`}></div>
      <div className={`${styles.tile} ${styles.tile_115}`}></div>
      <div className={`${styles.tile} ${styles.tile_116}`}></div>
    </div>
  );
}

export default Background;
